# Generated by Django 4.1 on 2023-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="census",
            name="adscription",
            field=models.CharField(default="Sin descripcion", max_length=100),
            preserve_default=False,
        ),
    ]
