# Generated by Django 4.1 on 2023-10-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0002_census_adscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="census",
            name="adscription",
            field=models.CharField(default="Sin descripcion", max_length=100),
        ),
    ]
