# Generated by Django 4.1 on 2023-10-24 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0003_alter_census_adscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="census",
            name="adscription",
        ),
    ]
